### ISSUE TITLE
Add the new key to the ssh-agent

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-mfa-cscs#4]
After the key is generated, automatically add it to the ssh-agent by `ssh-add ~/.ssh/cscs-key`. 
At the moment, I have to edit the `~/.ssh/config` to point to the `cscs-key`. If the ssh-agent contain the key, then the ssh-config file can kept simple and works charm with the new `ComputationalResourceWidget`.

**Comment by unkcpz** [comment]
I also add a milestone for the release of the first production version. I think we can register it on the aiidalab registry, or you think we do it after the release? @yakutovicha

**Comment by yakutovicha** [comment]
I was trying to add it to the ssh-agent in the first place, but it didn't work as expected.

Concerning the release, I think we can already make one. We can set it `0.1.0` to communicate that it is not yet a stable API.

**Comment by unkcpz** [comment]
> We can set it 0.1.0 to communicate that it is not yet a stable API.

Make sense to me! Let's do it. thanks.

**Comment by unkcpz** [comment]
Did you try not with `~` or `$HOME` for the path to the private key but like the code below? I did test the code and it can add the key to the agent. I'll open a PR for it. 

```python
subprocess.run(["ssh-add", "-t", "1d", "/home/jovyan/.ssh/id_rsa"] , check=True)
```

**Comment by yakutovicha** [comment]
> Did you try not with `~` or `$HOME` for the path to the private key but like the code below? I did test the code and it can add the key to the agent. I'll open a PR for it.
> 
> ```python
> subprocess.run(["ssh-add", "-t", "1d", "/home/jovyan/.ssh/id_rsa"] , check=True)
> ```

if that works, it is awesome 👍
